version: "3.8"
services:
  npm:
    build: 
      context: ./
      dockerfile: docker/node.Dockerfile
    entrypoint: ['npm']
    volumes:
      - ./:/code/quiz-api
  nest:
    build: 
      context: ./
      dockerfile: docker/node.Dockerfile
    entrypoint: ['nest']
    volumes:
      - ./:/code/quiz-api
  start:
    build: 
      context: ./
      dockerfile: docker/node.Dockerfile
    ports:
      - '3000:3000'
    command: ['npm', 'start']
    volumes:
      - ./:/code/quiz-api
    depends_on:
      - mongo
  start-dev:
    build: 
      context: ./
      dockerfile: docker/node.Dockerfile
    ports:
      - '3000:3000'
    command: ['npm', 'run', 'start:dev']
    volumes:
      - ./:/code/quiz-api
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: quiz
    volumes:
      - ./docker/dev/volumes/mongo:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/
    depends_on:
      - mongo